(()=>{
const run=async()=>{
 const settings=document.getElementById('settings');if(!settings||settings.dataset.akBlogFixed)return;settings.dataset.akBlogFixed='1';
 const style=document.createElement('style');style.textContent=`#settings .ak-blog-panel{background:#fff;border:1px solid #e4eaf2;border-radius:16px;padding:16px;margin-bottom:12px;box-shadow:0 10px 30px rgba(18,38,68,.06)}#settings .ak-blog-panel h2{margin:0;color:#0a1628;font-size:17px}.ak-blog-help{margin:5px 0;color:#68778b;font-size:10px;line-height:1.55}.ak-blog-form{display:grid;gap:9px;margin-top:12px}.ak-blog-form input,.ak-blog-form textarea{width:100%;box-sizing:border-box;background:#fff;color:#0a1628;border:1px solid #d8e1ec;border-radius:10px;padding:10px;font:inherit}.ak-blog-form textarea{min-height:110px;resize:vertical}.ak-blog-row{display:grid;grid-template-columns:1fr 1fr;gap:9px}.ak-blog-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.ak-blog-actions button{flex:1}.ak-blog-list{display:grid;gap:8px;margin-top:14px}.ak-blog-item{border:1px solid #e4eaf2;border-radius:12px;padding:12px;background:#f9fbfe}.ak-blog-item b{font-size:12px;color:#0a1628}.ak-blog-item small{display:block;color:#718096;font-size:9px;margin-top:4px}.ak-blog-msg{min-height:15px;margin-top:8px;color:#68778b;font-size:10px}@media(max-width:560px){.ak-blog-row{grid-template-columns:1fr}}`;
 document.head.appendChild(style);
 const panel=document.createElement('section');panel.className='ak-blog-panel';panel.innerHTML='<h2>Blog</h2><p class="ak-blog-help">Create and manage AkhiSave guides. Published posts appear on the public Blog and in the homepage Blog section.</p><div class="ak-blog-form"><input id="akBlogTitle" maxlength="140" placeholder="Post title"><div class="ak-blog-row"><input id="akBlogSlug" maxlength="120" placeholder="Slug, e.g. how-to-resize-an-image"><input id="akBlogCategory" maxlength="50" placeholder="Category, e.g. Image Tools"></div><div class="ak-blog-row"><input id="akBlogAuthor" maxlength="60" placeholder="Author"><input id="akBlogDate" type="date"></div><input id="akBlogSeoTitle" maxlength="160" placeholder="SEO title (optional)"><input id="akBlogSeoDesc" maxlength="260" placeholder="SEO description (optional)"><textarea id="akBlogExcerpt" maxlength="320" placeholder="Short excerpt / summary"></textarea><textarea id="akBlogContent" placeholder="Article content. Use blank lines between paragraphs."></textarea><label style="display:flex;align-items:center;gap:8px;font-size:11px;color:#40516a"><input id="akBlogPublished" type="checkbox" checked> Publish this post</label></div><div class="ak-blog-actions"><button id="akBlogNew" class="btn" type="button">+ New Post</button><button id="akBlogSave" class="btn primary" type="button">Save Post</button></div><div id="akBlogMsg" class="ak-blog-msg"></div><div id="akBlogList" class="ak-blog-list">Loading…</div>';settings.appendChild(panel);
 const $=id=>document.getElementById(id);let posts=[],editing='';
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const slugify=v=>String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,110);
 function clear(){editing='';['akBlogTitle','akBlogSlug','akBlogCategory','akBlogAuthor','akBlogSeoTitle','akBlogSeoDesc','akBlogExcerpt','akBlogContent'].forEach(id=>$(id).value='');$('akBlogDate').value=new Date().toISOString().slice(0,10);$('akBlogPublished').checked=true;$('akBlogMsg').textContent='New post ready.'}
 function fill(p){editing=p.slug;$('akBlogTitle').value=p.title||'';$('akBlogSlug').value=p.slug||'';$('akBlogCategory').value=p.category||'General';$('akBlogAuthor').value=p.author||'AkhiSave';$('akBlogDate').value=(p.date||'').slice(0,10);$('akBlogSeoTitle').value=p.seoTitle||'';$('akBlogSeoDesc').value=p.seoDescription||'';$('akBlogExcerpt').value=p.excerpt||'';$('akBlogContent').value=p.content||'';$('akBlogPublished').checked=p.published!==false;$('akBlogMsg').textContent='Editing: '+p.title}
 async function req(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.error||'Request failed');return d}
 async function load(){try{const d=await req('/api/admin/blog');posts=d.posts||[];$('akBlogList').innerHTML=posts.length?posts.map(p=>`<div class="ak-blog-item"><b>${esc(p.title)}</b><small>${esc(p.date||'')} · ${p.published===false?'Draft':'Published'} · /blog/${esc(p.slug)}</small><div class="ak-blog-actions"><button class="btn" data-edit="${esc(p.slug)}">Edit</button><button class="btn" data-delete="${esc(p.slug)}">Delete</button></div></div>`).join(''):'<div class="ak-blog-help">No blog posts yet.</div>';posts.forEach(p=>{});$('akBlogList').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>fill(posts.find(p=>p.slug===b.dataset.edit)||{}));$('akBlogList').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this post?'))return;try{await req('/api/admin/blog',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:b.dataset.delete})});$('akBlogMsg').textContent='Post deleted.';clear();load()}catch(e){$('akBlogMsg').textContent=e.message}})}catch(e){$('akBlogList').textContent=e.message}}
 $('akBlogTitle').oninput=()=>{if(!editing)$('akBlogSlug').value=slugify($('akBlogTitle').value)};
 $('akBlogNew').onclick=clear;
 $('akBlogSave').onclick=async()=>{try{const title=$('akBlogTitle').value.trim();const slug=slugify($('akBlogSlug').value||title);if(!title||!slug||!$('akBlogContent').value.trim())throw Error('Title, slug and article content are required.');const post={title,slug,category:$('akBlogCategory').value.trim()||'General',author:$('akBlogAuthor').value.trim()||'AkhiSave',date:$('akBlogDate').value||new Date().toISOString().slice(0,10),seoTitle:$('akBlogSeoTitle').value.trim(),seoDescription:$('akBlogSeoDesc').value.trim(),excerpt:$('akBlogExcerpt').value.trim(),content:$('akBlogContent').value,published:$('akBlogPublished').checked};await req('/api/admin/blog',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({post,editing})});editing=slug;$('akBlogMsg').textContent='Post saved successfully.';load()}catch(e){$('akBlogMsg').textContent=e.message}};
 clear();load();
 setTimeout(()=>{
   const blogBtn=document.querySelector('.bottom .bottom-btn[data-tab="blog"]');
   if(blogBtn){blogBtn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.getElementById('akAdminBlogTab')?.classList.add('active');document.querySelectorAll('.bottom .bottom-btn').forEach(x=>x.classList.toggle('active',x===blogBtn));history.replaceState(null,'','#akAdminBlogTab')},true)}
   const drawer=document.getElementById('drawer');
   const iconMap={Dashboard:'home',Tools:'tools',Settings:'settings',Blog:'blog',Categories:'tools',Analytics:'dashboard',Ads:'ads',Social:'social',More:'more'};
   const paths={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',tools:'<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.8 1.8 0 0 0 .35 2l.05.05-1.8 1.8-.05-.05a1.8 1.8 0 0 0-2-.35 1.8 1.8 0 0 0-1.1 1.65V20h-2.5v-.07a1.8 1.8 0 0 0-1.1-1.65 1.8 1.8 0 0 0-2 .35l-.05.05-1.8-1.8.05-.05a1.8 1.8 0 0 0 .35-2A1.8 1.8 0 0 0 6.15 13H6v-2h.15a1.8 1.8 0 0 0 1.65-1.1 1.8 1.8 0 0 0-.35-2l-.05-.05 1.8-1.8.05.05a1.8 1.8 0 0 0 2 .35A1.8 1.8 0 0 0 12.35 4.8V4h2.5v.8a1.8 1.8 0 0 0 1.1 1.65 1.8 1.8 0 0 0 2-.35l.05-.05 1.8 1.8-.05.05a1.8 1.8 0 0 0-.35 2 1.8 1.8 0 0 0 1.65 1.1H21v2h-.15a1.8 1.8 0 0 0-1.45 2z"/>',blog:'<path d="M5 4h10a4 4 0 0 1 4 4v12H9a4 4 0 0 1-4-4z"/><path d="M9 4v12a4 4 0 0 0 4 4M8 8h7M8 11h7"/>',more:'<circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/>'};
   if(drawer){drawer.querySelectorAll('a,.navlink').forEach(a=>{if(a.querySelector('svg'))return;const t=(a.textContent||'').trim().replace(/\s+/g,' ');const key=Object.keys(iconMap).find(k=>t.toLowerCase().includes(k.toLowerCase()));if(key&&paths[iconMap[key]]){const s=document.createElement('span');s.innerHTML='<svg class="ak-bottom-icon" viewBox="0 0 24 24" aria-hidden="true">'+paths[iconMap[key]]+'</svg>';s.style.cssText='display:inline-block;vertical-align:middle;margin-right:8px;width:17px;height:17px;color:currentColor';a.prepend(s)}})}
 },500);
};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
