import tools from "./tools-entry.js";
import { analyticsResponse } from "./analytics-core.js";

const PANEL = `
<style id="akhisave-admin-suite-style">
#ak-suite{display:grid;gap:12px}.aks-card{background:#fff;border:1px solid #e8edf5;border-radius:16px;padding:16px}.aks-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.aks-head h2{margin:0;font-size:17px;color:#10233f}.aks-head p{margin:4px 0 0;color:#718096;font-size:11px}.aks-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.aks-stat{padding:13px;border-radius:13px;background:#f7faff;border:1px solid #e8eef8}.aks-stat span{font-size:9px;color:#718096;font-weight:800}.aks-stat b{display:block;margin-top:5px;font-size:20px;color:#123c7a}.aks-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 0;border-bottom:1px solid #edf1f6}.aks-row:last-child{border-bottom:0}.aks-row b{font-size:11px;color:#20324b}.aks-row small{display:block;color:#7a8798;font-size:9px;margin-top:2px}.aks-btn{border:0;border-radius:9px;padding:8px 11px;background:#1769e0;color:#fff;font-size:10px;font-weight:800}.aks-btn.alt{background:#eef5ff;color:#1769e0}.aks-input{width:100%;box-sizing:border-box;padding:9px 10px;border:1px solid #dfe6ef;border-radius:9px;background:#fff;color:#17253a;font-size:10px}.aks-form{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:12px}.aks-list{display:grid;gap:7px;margin-top:10px}.aks-tag{display:inline-flex;align-items:center;gap:7px;padding:7px 9px;background:#f5f8fc;border:1px solid #e3e9f1;border-radius:9px;font-size:10px;color:#26364e}.aks-danger{color:#d33b4b;background:#fff1f2}.aks-note{font-size:10px;line-height:1.6;color:#6d7b8e;margin-top:10px}.aks-ok{color:#16864a}.aks-warn{color:#b06b00}.aks-bad{color:#c72f42}.aks-table{width:100%;border-collapse:collapse;font-size:10px;margin-top:10px}.aks-table th,.aks-table td{text-align:left;padding:8px;border-bottom:1px solid #edf1f6}.aks-table th{color:#64748b;font-size:9px}.aks-hide{display:none!important}@media(max-width:700px){.aks-grid{grid-template-columns:1fr 1fr}.aks-form{grid-template-columns:1fr}.aks-head{align-items:flex-start;flex-direction:column}}
</style>
<section id="ak-suite">
<div class="aks-card" data-panel="categories"><div class="aks-head"><div><h2>Categories</h2><p>Create, rename and remove tool categories. Categories are stored in KV.</p></div></div><div class="aks-form"><input id="aksCatName" class="aks-input" placeholder="New category name"><button id="aksCatAdd" class="aks-btn">+ Add</button></div><div id="aksCats" class="aks-list">Loading…</div></div>
<div class="aks-card" data-panel="dashboard"><div class="aks-head"><div><h2>Dashboard & Analytics</h2><p>Live admin summary from the existing analytics and tool registry APIs.</p></div><button id="aksDashRefresh" class="aks-btn alt">↻ Refresh</button></div><div class="aks-grid"><div class="aks-stat"><span>TOTAL TOOLS</span><b id="aksToolCount">—</b></div><div class="aks-stat"><span>ENABLED TOOLS</span><b id="aksToolEnabled">—</b></div><div class="aks-stat"><span>7-DAY REQUESTS</span><b id="aksRequests">—</b></div></div><div id="aksDashNote" class="aks-note">Loading analytics…</div></div>
<div class="aks-card" data-panel="website"><div class="aks-head"><div><h2>Website Settings</h2><p>Control maintenance mode and the public announcement.</p></div><button id="aksSiteSave" class="aks-btn">Save</button></div><div class="aks-row"><div><b>Maintenance Mode</b><small>Show the site's maintenance state.</small></div><input id="aksMaintenance" type="checkbox"></div><div style="margin-top:10px"><label style="font-size:9px;font-weight:800;color:#66758a">ANNOUNCEMENT / BANNER</label><input id="aksAnnouncement" class="aks-input" style="margin-top:5px" placeholder="Optional announcement"></div><div id="aksSiteMsg" class="aks-note"></div></div>
<div class="aks-card" data-panel="seo"><div class="aks-head"><div><h2>SEO</h2><p>Global homepage title and meta description.</p></div><button id="aksSeoSave" class="aks-btn">Save</button></div><div style="margin-top:10px"><label style="font-size:9px;font-weight:800;color:#66758a">HOMEPAGE TITLE</label><input id="aksSeoTitle" class="aks-input" style="margin-top:5px"></div><div style="margin-top:10px"><label style="font-size:9px;font-weight:800;color:#66758a">META DESCRIPTION</label><textarea id="aksSeoDesc" class="aks-input" style="margin-top:5px;min-height:80px;resize:vertical"></textarea></div><div id="aksSeoMsg" class="aks-note"></div></div>
<div class="aks-card" data-panel="health"><div class="aks-head"><div><h2>System Health</h2><p>Read-only health checks. No fake “fix” actions are shown.</p></div><button id="aksHealthRefresh" class="aks-btn alt">↻ Check</button></div><div id="aksHealth" class="aks-list">Checking…</div></div>
<div class="aks-card" data-panel="security"><div class="aks-head"><div><h2>Security</h2><p>Admin-session and API security status. Secrets are never displayed.</p></div><button id="aksSecRefresh" class="aks-btn alt">↻ Check</button></div><div id="aksSecurity" class="aks-list">Checking…</div><div class="aks-note">API keys and passwords are intentionally not exposed in the admin UI.</div></div>
</section>`;

function ok(v){return v && v.success !== false}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}})}
const blankAnalytics=()=>({visitors:0,newVisitors:0,returning:0,pageViews:0,attempts:0,downloads:0,failures:0,tools:{}});
async function readA(env,key){if(!env.AKHISAVE_SETTINGS)return blankAnalytics();try{const raw=await env.AKHISAVE_SETTINGS.get(key);const a=raw?JSON.parse(raw):{};return{...blankAnalytics(),...a,tools:{...(a.tools||{})}}}catch{return blankAnalytics();}}
async function rangeAnalytics(env,days,start,end){const out=[];const all={};let endDate=end?new Date(end+'T00:00:00Z'):new Date();let startDate=start?new Date(start+'T00:00:00Z'):new Date(endDate);if(!start)startDate.setUTCDate(endDate.getUTCDate()-(Math.max(1,Math.min(365,days))-1));if(startDate>endDate){const x=startDate;startDate=endDate;endDate=x}const maxDays=Math.min(365,Math.max(1,Math.floor((endDate-startDate)/86400000)+1));for(let i=0;i<maxDays;i++){const d=new Date(startDate);d.setUTCDate(startDate.getUTCDate()+i);const a=await readA(env,`analytics:${d.toISOString().slice(0,10)}`);out.push({date:d.toISOString().slice(0,10),visitors:a.visitors,pageViews:a.pageViews,attempts:a.attempts,downloads:a.downloads,failures:a.failures});Object.entries(a.tools).forEach(([k,v])=>all[k]=(all[k]||0)+v)}const last=out[out.length-1]||{date:endDate.toISOString().slice(0,10),visitors:0,pageViews:0,attempts:0,downloads:0,failures:0};const lastA=await readA(env,`analytics:${last.date}`);return{success:true,today:{...last,newVisitors:lastA.newVisitors,returning:lastA.returning,attempts:lastA.attempts},days:out,topTools:all};}

export default {async fetch(request,env,ctx){
  const u=new URL(request.url);
  if(u.pathname.startsWith('/api/admin/')){
    const status=await tools.fetch(new Request(new URL('/api/admin/status',request.url),{headers:request.headers}),env,ctx);
    if(!status.ok)return json({success:false,error:'Unauthorized'},401);
    if(u.pathname==='/api/admin/categories'){
      const key='admin_categories';
      if(request.method==='GET')return json({success:true,categories:JSON.parse(await env.AKHISAVE_SETTINGS.get(key)||'[]')});
      if(request.method==='PUT'){
        const body=await request.json().catch(()=>({}));
        const cats=Array.isArray(body.categories)?body.categories.map((x,i)=>({id:String(x.id||('cat-'+Date.now()+'-'+i)).slice(0,80),name:String(x.name||'').trim().slice(0,60)})).filter(x=>x.name):[];
        await env.AKHISAVE_SETTINGS.put(key,JSON.stringify(cats));return json({success:true,categories:cats});
      }
    }
    if(u.pathname==='/api/admin/analytics'){
      return analyticsResponse(env,u);
    }
    if(u.pathname==='/api/admin/health')return json({success:true,checks:{kv:Boolean(env.AKHISAVE_SETTINGS),assets:Boolean(env.ASSETS),adminAuth:status.ok},note:'Health checks report configuration availability only.'});
    if(u.pathname==='/api/admin/security')return json({success:true,checks:{adminSession:true,https:u.protocol==='https:',secretExposure:false},note:'Secrets are server-side and are not returned.'});
  }
  const response=await tools.fetch(request,env,ctx);
  if(request.method!=='GET'||(u.pathname!=='/admin.html'&&u.pathname!=='/admin'))return response;
  const ct=response.headers.get('content-type')||'';if(!ct.includes('text/html'))return response;
  let html=await response.text();if(!/<title>AkhiSave Admin<\/title>/i.test(html))return new Response(html,{status:response.status,headers:response.headers});
  const script=`<script>(function(){const $=x=>document.getElementById(x);async function req(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.error||'Request failed');return d}function msg(id,t){$(id).textContent=t}
async function cats(){try{const d=await req('/api/admin/categories');const a=d.categories||[];$('aksCats').innerHTML=a.length?a.map((c,i)=>'<div class="aks-tag"><span>'+esc(c.name)+'</span><button class="aks-btn aks-danger" data-cat="'+i+'">Delete</button></div>').join(''):'<div class="aks-note">No categories yet.</div>';$('aksCats').querySelectorAll('[data-cat]').forEach(b=>b.onclick=async()=>{a.splice(+b.dataset.cat,1);await req('/api/admin/categories',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({categories:a})});cats()})}catch(e){$('aksCats').textContent=e.message}}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('aksCatAdd').onclick=async()=>{const n=$('aksCatName').value.trim();if(!n)return;const d=await req('/api/admin/categories');const a=d.categories||[];if(!a.some(x=>x.name.toLowerCase()===n.toLowerCase()))a.push({id:'cat-'+Date.now(),name:n});await req('/api/admin/categories',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({categories:a})});$('aksCatName').value='';cats()};
async function dash(){try{const t=await req('/api/admin/tools'),a=await req('/api/admin/analytics');const ts=t.tools||[];$('aksToolCount').textContent=ts.length;$('aksToolEnabled').textContent=ts.filter(x=>x.enabled!==false).length;let total=(a.days||[]).reduce((s,x)=>s+(Number(x.attempts)||0),0);$('aksRequests').textContent=total.toLocaleString();$('aksDashNote').textContent='Analytics endpoint connected. Detailed fields returned by the backend are preserved.'}catch(e){$('aksDashNote').textContent='Analytics unavailable: '+e.message}};
async function site(){try{const d=await req('/api/admin/settings');const s=d.settings||d;$('aksMaintenance').checked=!!s.maintenance;$('aksAnnouncement').value=s.announcement||'';$('aksSeoTitle').value=s.seo?.title||'';$('aksSeoDesc').value=s.seo?.description||''}catch(e){msg('aksSiteMsg',e.message)}}$('aksSiteSave').onclick=async()=>{try{const d=await req('/api/admin/settings');const s=d.settings||d;s.maintenance=$('aksMaintenance').checked;s.announcement=$('aksAnnouncement').value;await req('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)});msg('aksSiteMsg','Website settings saved.')}catch(e){msg('aksSiteMsg',e.message)}};$('aksSeoSave').onclick=async()=>{try{const d=await req('/api/admin/settings');const s=d.settings||d;s.seo=s.seo||{};s.seo.title=$('aksSeoTitle').value;s.seo.description=$('aksSeoDesc').value;await req('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)});msg('aksSeoMsg','SEO settings saved.')}catch(e){msg('aksSeoMsg',e.message)}};
async function health(){try{const d=await req('/api/admin/health');$('aksHealth').innerHTML=Object.entries(d.checks).map(([k,v])=>'<div class="aks-row"><b>'+esc(k)+'</b><span class="'+(v?'aks-ok':'aks-bad')+'">'+(v?'OK':'NOT AVAILABLE')+'</span></div>').join('')}catch(e){$('aksHealth').textContent=e.message}}async function sec(){try{const d=await req('/api/admin/security');$('aksSecurity').innerHTML=Object.entries(d.checks).map(([k,v])=>'<div class="aks-row"><b>'+esc(k)+'</b><span class="'+(v?'aks-ok':'aks-bad')+'">'+(v?'OK':'CHECK')+'</span></div>').join('')}catch(e){$('aksSecurity').textContent=e.message}}$('aksDashRefresh').onclick=dash;$('aksHealthRefresh').onclick=health;$('aksSecRefresh').onclick=sec;function init(){const main=document.querySelector('main.wrap');if(!main)return;const suite=document.createElement('div');suite.innerHTML=${JSON.stringify(PANEL)};main.appendChild(suite.firstElementChild);cats();dash();site();health();sec()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();</script>`;
  html=html.replace('</body>',script+'</body>');const h=new Headers(response.headers);h.delete('content-length');h.set('Cache-Control','no-store');return new Response(html,{status:response.status,headers:h});
}};
