(()=>{
  const run=async()=>{
    const settings=document.getElementById('settings');
    if(!settings||settings.dataset.akSocialFixed)return;
    settings.dataset.akSocialFixed='1';
    const style=document.createElement('style');
    style.textContent=`#settings .ak-social-panel{background:#fff;border:1px solid #e4eaf2;border-radius:16px;padding:16px;margin-bottom:12px;box-shadow:0 10px 30px rgba(18,38,68,.06)}#settings .ak-social-panel h2{margin:0;color:#0a1628;font-size:17px}#settings .ak-social-panel p{margin:5px 0;color:#68778b;font-size:10px;line-height:1.55}.ak-social-item{border:1px solid #e4eaf2;border-radius:12px;padding:12px;margin-top:10px;background:#f9fbfe}.ak-social-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.ak-social-copy b{display:block;color:#0a1628;font-size:12px}.ak-social-copy span{display:block;color:#718096;font-size:10px;margin-top:3px}.ak-social-fields{display:grid;grid-template-columns:90px 1fr;gap:8px;margin-top:10px}.ak-social-fields input{width:100%;box-sizing:border-box;background:#fff;color:#0a1628;border:1px solid #d8e1ec;border-radius:10px;padding:10px;font:inherit}.ak-social-fields input:focus{border-color:#1677ff;outline:none}.ak-social-add{margin-top:12px;width:100%}.ak-social-actions{margin-top:12px}.ak-social-msg{margin-top:8px;color:#68778b;font-size:10px;min-height:14px}@media(max-width:560px){.ak-social-fields{grid-template-columns:1fr}}`;
    document.head.appendChild(style);
    const panel=document.createElement('section');panel.className='ak-social-panel';
    panel.innerHTML='<h2>Social Media</h2><p>Add social media links to show on the public website. Turn each one ON/OFF. Use + Add Social Media when you want to add more platforms later.</p><div id="akSocialList"></div><button id="akSocialAdd" class="btn" style="width:100%;margin-top:12px">+ Add Social Media</button><div class="ak-social-actions"><button id="akSocialSave" class="btn primary" style="width:100%">Save Social Media</button></div><div id="akSocialMsg" class="ak-social-msg"></div>';
    settings.appendChild(panel);
    const list=document.getElementById('akSocialList');
    const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    const make=(x={name:'',url:'',enabled:true})=>{const el=document.createElement('div');el.className='ak-social-item';el.innerHTML='<div class="ak-social-head"><div class="ak-social-copy"><b class="akSocialName">'+esc(x.name||'Social Media')+'</b><span>Show this link on the website</span></div><input class="switch akSocialEnabled" type="checkbox" '+(x.enabled!==false?'checked':'')+'></div><div class="ak-social-fields"><input class="akSocialLabel" maxlength="40" placeholder="Platform" value="'+esc(x.name||'')+'"><input class="akSocialUrl" maxlength="500" placeholder="https://..." value="'+esc(x.url||'')+'"></div>';el.querySelector('.akSocialLabel').oninput=e=>el.querySelector('.akSocialName').textContent=e.target.value||'Social Media';list.appendChild(el);};
    async function load(){try{const r=await fetch('/api/social-links',{cache:'no-store'});const d=await r.json();list.innerHTML='';(Array.isArray(d.links)?d.links:[]).forEach(make);if(!list.children.length){make({name:'YouTube',url:'',enabled:true});make({name:'Instagram',url:'',enabled:true});}}catch{make({name:'YouTube',url:'',enabled:true});make({name:'Instagram',url:'',enabled:true});}}
    document.getElementById('akSocialAdd').onclick=()=>make({name:'',url:'',enabled:true});
    document.getElementById('akSocialSave').onclick=async()=>{const links=[...list.children].map(el=>({name:el.querySelector('.akSocialLabel').value.trim(),url:el.querySelector('.akSocialUrl').value.trim(),enabled:el.querySelector('.akSocialEnabled').checked})).filter(x=>x.name&&x.url).slice(0,20);const msg=document.getElementById('akSocialMsg');try{const r=await fetch('/api/admin/social-links',{method:'PUT',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({links}),cache:'no-store'});const d=await r.json();if(!r.ok||d.success===false)throw Error(d.error||'Could not save social links.');msg.textContent='Social media settings saved.';}catch(e){msg.textContent=e.message;}};
    await load();
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
