(()=>{
  if(window.__AKHISAVE_ADSENSE_ADMIN_V2__)return;
  window.__AKHISAVE_ADSENSE_ADMIN_V2__=true;
  const DEFAULT_CODE='<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3063864969990896" crossorigin="anonymous"></script>';
  const $=id=>document.getElementById(id);
  async function api(path,opt){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(opt&&opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.error||'Request failed');return d;}
  function card(){return `<section id="akAdsenseCard" style="margin:16px 0;padding:20px;border:1px solid #dfe5ee;border-radius:18px;background:#fff;color:#142033;box-shadow:0 8px 28px rgba(20,32,51,.08)"><div style="display:flex;align-items:flex-start;justify-content:space-between;gap:14px;flex-wrap:wrap"><div><div style="font-size:20px;font-weight:900;letter-spacing:-.4px">Google AdSense</div><div style="margin-top:5px;color:#68778b;font-size:11px;line-height:1.6">Site verification and AdSense code control</div></div><span id="akAdsenseStatus" style="display:inline-flex;align-items:center;padding:7px 10px;border-radius:999px;background:#eefaf4;color:#16824b;border:1px solid #c9efd9;font-size:10px;font-weight:900">ON</span></div><div style="margin-top:16px;padding:13px;border:1px solid #e6ebf2;border-radius:13px;background:#f8fafc;display:flex;align-items:center;justify-content:space-between;gap:12px"><div><div style="font-size:12px;font-weight:850">Enable AdSense</div><div style="margin-top:3px;color:#7a8798;font-size:10px">Adds the Google AdSense verification code to public pages.</div></div><label style="position:relative;width:46px;height:25px;display:block;flex:none"><input id="akAdsenseEnabled" type="checkbox" style="opacity:0;width:0;height:0"><span style="position:absolute;inset:0;border-radius:99px;background:#cbd5e1;cursor:pointer;transition:.2s"></span><i id="akAdsenseKnob" style="position:absolute;top:3px;left:3px;width:19px;height:19px;border-radius:50%;background:#fff;box-shadow:0 2px 6px #0002;transition:.2s;pointer-events:none"></i></label></div><div style="margin-top:14px"><label style="display:block;margin-bottom:6px;color:#66758a;font-size:9px;font-weight:900;letter-spacing:.6px">ADSENSE VERIFICATION CODE</label><textarea id="akAdsenseCode" style="width:100%;min-height:92px;padding:12px;border:1px solid #dbe3ed;border-radius:11px;background:#fff;color:#142033;font:11px ui-monospace,SFMono-Regular,Menlo,monospace;resize:vertical;outline:0"></textarea></div><div style="display:flex;align-items:center;gap:9px;margin-top:12px;flex-wrap:wrap"><button id="akAdsenseSave" type="button" style="border:0;border-radius:10px;padding:11px 17px;background:#1677ff;color:#fff;font-size:11px;font-weight:900;cursor:pointer">Save AdSense Settings</button><span id="akAdsenseMsg" style="color:#68778b;font-size:10px"></span></div><div style="margin-top:10px;color:#8a96a7;font-size:9px;line-height:1.6">Use the exact code from your Google AdSense account. After publishing, verify the site from AdSense.</div></section>`;}
  function paint(){const on=!!$('akAdsenseEnabled')?.checked;const s=$('akAdsenseStatus'),k=$('akAdsenseKnob'),track=k?.previousElementSibling;if(s){s.textContent=on?'ON':'OFF';s.style.background=on?'#eefaf4':'#f1f4f7';s.style.color=on?'#16824b':'#6b7788';s.style.borderColor=on?'#c9efd9':'#dbe2ea';}if(track){track.style.background=on?'#1677ff':'#cbd5e1';}if(k)k.style.left=on?'24px':'3px';}
  async function load(){try{const d=await api('/api/admin/adsense');$('akAdsenseEnabled').checked=!!d.adsense?.enabled;$('akAdsenseCode').value=d.adsense?.code||DEFAULT_CODE;paint();}catch(e){$('akAdsenseMsg').textContent=e.message;}}
  async function save(){const b=$('akAdsenseSave');b.disabled=true;b.textContent='Saving…';try{const d=await api('/api/admin/adsense',{method:'PUT',body:JSON.stringify({enabled:$('akAdsenseEnabled').checked,code:$('akAdsenseCode').value})});$('akAdsenseMsg').textContent=d.message||'AdSense settings saved.';paint();}catch(e){$('akAdsenseMsg').textContent='Save failed: '+e.message;}b.disabled=false;b.textContent='Save AdSense Settings';}
  function mount(){if(document.getElementById('akAdsenseCard'))return;const host=document.querySelector('#dashboard')||document.querySelector('#ak-suite')||document.querySelector('main.wrap')||document.querySelector('main');if(!host)return;host.insertAdjacentHTML('afterbegin',card());$('akAdsenseSave').onclick=save;$('akAdsenseEnabled').onchange=paint;paint();load();}
  function boot(){mount();const obs=new MutationObserver(()=>mount());obs.observe(document.documentElement,{childList:true,subtree:true});[300,800,1500,3000,5000].forEach(t=>setTimeout(mount,t));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
