const blank=()=>({visitors:0,newVisitors:0,returning:0,pageViews:0,attempts:0,downloads:0,failures:0,tools:{},pages:{},visitorIds:[],newVisitorIds:[],countries:{},devices:{},hours:{}});
async function read(env,key){if(!env.AKHISAVE_SETTINGS)return blank();try{const raw=await env.AKHISAVE_SETTINGS.get(key);const a=raw?JSON.parse(raw):{};return{...blank(),...a,visitorIds:Array.isArray(a.visitorIds)?a.visitorIds:[],newVisitorIds:Array.isArray(a.newVisitorIds)?a.newVisitorIds:[],tools:{...(a.tools||{})},pages:{...(a.pages||{})},countries:{...(a.countries||{})},devices:{...(a.devices||{})},hours:{...(a.hours||{})}}}catch{return blank()}}
async function write(env,key,a){if(env.AKHISAVE_SETTINGS)await env.AKHISAVE_SETTINGS.put(key,JSON.stringify(a))}
const dayKey=d=>`analytics:${d.toISOString().slice(0,10)}`;const trackingStartKey='analytics:visitor-tracking-start';
function visitorCookie(request){const c=request.headers.get('Cookie')||'';const m=c.match(/(?:^|;\s*)akhisave_vid_v2=([^;]+)/);return m?m[1]:''}
function deviceType(request){const ua=(request.headers.get('User-Agent')||'').toLowerCase();if(/ipad|tablet|playbook|silk/.test(ua))return'Tablet';if(/mobi|iphone|ipod|android.*mobile|windows phone/.test(ua))return'Mobile';return'Desktop'}
function countryOf(request){return String(request.cf?.country||request.headers.get('CF-IPCountry')||'Unknown').toUpperCase().slice(0,2)||'Unknown'}
function localHour(request,now){try{const tz=request.cf?.timezone;if(tz){const h=new Intl.DateTimeFormat('en-US',{timeZone:tz,hour:'2-digit',hour12:false}).format(now);return String(Number(h)).padStart(2,'0')}}catch{}return String(now.getUTCHours()).padStart(2,'0')}
export async function track(request,env){
 if(request.method!=='POST')return Response.json({success:false,error:'Method not allowed'},{status:405,headers:{'Cache-Control':'no-store'}});
 try{const body=await request.json(),event=String(body.event||''),tool=String(body.tool||'unknown').slice(0,50),page=String(body.page||'').trim().slice(0,120);if(!['page_view','download_attempt','download_success','download_failure'].includes(event))return Response.json({success:false,error:'Invalid event.'},{status:400});const now=new Date(),today=now.toISOString().slice(0,10),key=dayKey(now),a=await read(env,key),vid=visitorCookie(request),device=deviceType(request),country=countryOf(request),hour=localHour(request,now);if(event==='page_view'){a.pageViews++;if(page)a.pages[page]=(a.pages[page]||0)+1}else if(event==='download_attempt')a.attempts++;else if(event==='download_success')a.downloads++;else a.failures++;if(tool&&tool!=='unknown'&&(event==='download_attempt'||event==='download_success'))a.tools[tool]=(a.tools[tool]||0)+1;let setCookie='';if(event==='page_view'){const id=vid||crypto.randomUUID();if(!a.visitorIds.includes(id))a.visitorIds.push(id);a.visitors=a.visitorIds.length;if(!vid&&!a.newVisitorIds.includes(id))a.newVisitorIds.push(id);a.newVisitors=a.newVisitorIds.length;a.returning=Math.max(0,a.visitors-a.newVisitors);a.countries[country]=(a.countries[country]||0)+1;a.devices[device]=(a.devices[device]||0)+1;a.hours[hour]=(a.hours[hour]||0)+1;if(env.AKHISAVE_SETTINGS){try{await env.AKHISAVE_SETTINGS.put(`analytics:active:${id}`,'',{expirationTtl:600,metadata:{country,device}})}catch{}const existing=await env.AKHISAVE_SETTINGS.get(trackingStartKey);if(!existing)await env.AKHISAVE_SETTINGS.put(trackingStartKey,today)}if(!vid)setCookie=`akhisave_vid_v2=${id}; Path=/; Max-Age=31536000; Secure; SameSite=Lax`;}await write(env,key,a);const h=new Headers({'Content-Type':'application/json','Cache-Control':'no-store'});if(setCookie)h.append('Set-Cookie',setCookie);return new Response(JSON.stringify({success:true}),{status:200,headers:h});}catch{return Response.json({success:false,error:'Tracking failed.'},{status:400,headers:{'Cache-Control':'no-store'}})}}
function validDate(s){return /^\d{4}-\d{2}-\d{2}$/.test(s||'')?s:''}
async function activeAudience(env){const out={activeNow:0,countries:{},devices:{}};if(!env.AKHISAVE_SETTINGS)return out;try{let cursor;do{const r=await env.AKHISAVE_SETTINGS.list({prefix:'analytics:active:',limit:1000,...(cursor?{cursor}:{})});for(const k of r.keys||[]){if(k.expiration&&k.expiration*1000>Date.now()){out.activeNow++;const m=k.metadata||{};if(m.country)out.countries[m.country]=(out.countries[m.country]||0)+1;if(m.device)out.devices[m.device]=(out.devices[m.device]||0)+1}}cursor=r.list_complete?null:r.cursor}while(cursor)}catch{}return out}
export async function range(env,days,start,end){let endDate=end?new Date(end+'T00:00:00Z'):new Date(),startDate=start?new Date(start+'T00:00:00Z'):new Date(endDate);if(!start)startDate.setUTCDate(endDate.getUTCDate()-(Math.max(1,Math.min(365,Number(days)||7))-1));if(startDate>endDate){const x=startDate;startDate=endDate;endDate=x}const max=Math.min(365,Math.max(1,Math.floor((endDate-startDate)/86400000)+1)),rows=[],vis=new Set(),newVis=new Set(),tools={},pages={},countries={},devices={},hours={};let pageViews=0,attempts=0,downloads=0,failures=0,trackingStart='';if(env.AKHISAVE_SETTINGS)trackingStart=await env.AKHISAVE_SETTINGS.get(trackingStartKey)||'';for(let i=0;i<max;i++){const d=new Date(startDate);d.setUTCDate(startDate.getUTCDate()+i);const a=await read(env,dayKey(d));a.visitorIds.forEach(x=>vis.add(x));a.newVisitorIds.forEach(x=>newVis.add(x));pageViews+=Number(a.pageViews)||0;attempts+=Number(a.attempts)||0;downloads+=Number(a.downloads)||0;failures+=Number(a.failures)||0;Object.entries(a.tools||{}).forEach(([k,v])=>tools[k]=(tools[k]||0)+(Number(v)||0));Object.entries(a.pages||{}).forEach(([k,v])=>pages[k]=(pages[k]||0)+(Number(v)||0));Object.entries(a.countries||{}).forEach(([k,v])=>countries[k]=(countries[k]||0)+(Number(v)||0));Object.entries(a.devices||{}).forEach(([k,v])=>devices[k]=(devices[k]||0)+(Number(v)||0));Object.entries(a.hours||{}).forEach(([k,v])=>hours[k]=(hours[k]||0)+(Number(v)||0));rows.push({date:d.toISOString().slice(0,10),visitors:a.visitors||a.visitorIds.length,pageViews:a.pageViews||0,attempts:a.attempts||0,downloads:a.downloads||0,failures:a.failures||0,newVisitors:a.newVisitors||a.newVisitorIds.length,returning:Math.max(0,(a.visitors||a.visitorIds.length)-(a.newVisitors||a.newVisitorIds.length))})}const rangeStart=startDate.toISOString().slice(0,10),ready=!!trackingStart&&trackingStart<=rangeStart,summary=ready?{visitors:vis.size,newVisitors:newVis.size,returning:Math.max(0,vis.size-newVis.size),pageViews,attempts,downloads,failures}:{visitors:null,newVisitors:null,returning:null,pageViews,attempts,downloads,failures},active=await activeAudience(env);return{success:true,today:rows[rows.length-1]||{date:'',visitors:0,newVisitors:0,returning:0,pageViews:0,attempts:0,downloads:0,failures:0},days:rows,summary,tracking:{ready,start:trackingStart||null},topTools:tools,pages,audience:{activeNow:active.activeNow,countries,devices,hours,activeCountries:active.countries,activeDevices:active.devices}}}
export function analyticsResponse(env,url){const days=Math.min(365,Math.max(1,Number(url.searchParams.get('days')||7)));const start=validDate(url.searchParams.get('start')),end=validDate(url.searchParams.get('end'));return range(env,days,start,end).then(data=>Response.json(data,{headers:{'Cache-Control':'no-store'}}));}
