import base from "./brand-final.js";

function tokenClass(block, token){
  const m=block.match(/\bclass=["']([^"']*)["']/i);
  return !!(m && new RegExp("(?:^|\\s)"+token+"(?:\\s|$)","i").test(m[1]));
}

async function fixMenu(response){
  const type=response.headers.get("content-type")||"";
  if(!type.includes("text/html")) return response;
  let html=await response.text();
  if(/<title>AkhiSave Admin<\/title>/i.test(html)) return response;
  html=html.replace(/<script\b[^>]*id=["'](?:akhisave-mobile-menu|akhisave-premium-menu-links|akhisave-menu-fix-script)["'][^>]*>[\s\S]*?<\/script>/gi,"");
  html=html.replace(/<style\b[^>]*id=["'](?:akhisave-mobile-menu-css|akhisave-premium-menu-css|akhisave-menu-fix-css)["'][^>]*>[\s\S]*?<\/style>/gi,"");
  html=html.replace(/<button\b[^>]*>[\s\S]*?<\/button>/gi,(block)=>{if(tokenClass(block,"akhisave-menu-btn")||tokenClass(block,"menu")||tokenClass(block,"menuBtn"))return "";return block});
  html=html.replace(/<div\b[^>]*id=["']akhisaveMenuPanel["'][^>]*>[\s\S]*?<\/div>/gi,"");
  if(!/<header\b/i.test(html))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});

  const markup=`<button class="akhisave-menu-btn" id="akhisaveMenuBtn" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button><div id="akhisaveMenuPanel" aria-hidden="true"></div>`;
  const navinOpen=/<div\b[^>]*class=["'][^"']*(?:^|\s)navin(?:\s|$)[^"']*["'][^>]*>/i;
  if(navinOpen.test(html))html=html.replace(navinOpen,(m)=>m+markup);else html=html.replace(/<\/header>/i,markup+"</header>");

  const css=`<style id="akhisave-menu-fix-css">
.akhisave-menu-btn{display:flex!important;width:48px;height:48px;flex:0 0 48px;border:1px solid #d8e1ec;background:linear-gradient(180deg,#fff,#f8fbff);border-radius:14px;align-items:center;justify-content:center;flex-direction:column;gap:5px;cursor:pointer;padding:0;box-shadow:0 7px 20px rgba(18,38,68,.09);position:fixed!important;right:18px!important;top:17px!important;z-index:100003!important}.akhisave-menu-btn:active{transform:scale(.96)}.akhisave-menu-btn span{display:block;width:22px;height:2.5px;background:#122033;border-radius:4px;transition:transform .18s ease,opacity .18s ease}.akhisave-menu-btn[aria-expanded="true"] span:nth-child(2){opacity:0}.akhisave-menu-btn[aria-expanded="true"] span:first-child{transform:translateY(7.5px) rotate(45deg)}.akhisave-menu-btn[aria-expanded="true"] span:last-child{transform:translateY(-7.5px) rotate(-45deg)}
#akhisaveMenuPanel{display:none!important;position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;padding:96px 24px 35px!important;background:#fff!important;z-index:100002!important;overflow:auto!important}#akhisaveMenuPanel.open{display:block!important}#akhisaveMenuPanel .menu-head{max-width:900px;margin:0 auto 26px;padding:0 4px}.menu-head img{width:205px;height:66px;object-fit:contain;display:block}.menu-list{max-width:900px;margin:0 auto}.menu-group{border-bottom:1px solid #e4eaf2}.menu-group>a,.menu-toggle{width:100%;display:flex;align-items:center;justify-content:space-between;padding:19px 4px;border:0;background:none;text-decoration:none;color:#102039;font-size:22px;font-weight:800;text-align:left;cursor:pointer}.menu-toggle .arrow{font-size:22px;color:#1677ff;transition:transform .18s ease}.menu-group.open .menu-toggle .arrow{transform:rotate(180deg)}.submenu{display:none;padding:0 0 13px 14px}.menu-group.open .submenu{display:block}.submenu a{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:12px 10px;text-decoration:none;color:#536175;font-size:14px;font-weight:700;border-radius:10px}.submenu a:hover{background:#f2f7ff;color:#0876ff}.soon{font-size:10px;color:#1677ff;font-weight:900;white-space:nowrap}.menu-note{max-width:900px;margin:24px auto 0;padding:13px 4px;color:#7a8798;font-size:11px}@media(max-width:760px){.akhisave-menu-btn{right:12px!important;top:14px!important}.navin{min-height:76px!important;padding:0 13px!important}.brand img{width:190px!important;height:62px!important}.brand-logo-full{max-width:calc(100% - 62px)!important}.menu-head img{width:190px;height:62px}.menu-group>a,.menu-toggle{font-size:20px;padding:17px 2px}.submenu a{font-size:13px}}@media(min-width:761px){.akhisave-menu-btn{right:24px!important;top:17px!important}}
</style>`;
  html=html.replace(/<\/head>/i,css+"</head>");

  const script=`<script id="akhisave-menu-fix-script">(function(){function init(){var b=document.getElementById('akhisaveMenuBtn'),p=document.getElementById('akhisaveMenuPanel');if(!b||!p||b.dataset.bound==='1')return;b.dataset.bound='1';p.innerHTML='<div class="menu-head"><a href="/" aria-label="AkhiSave home"><img src="/LogoName.png" alt="AkhiSave"></a></div><div class="menu-list"><div class="menu-group"><button class="menu-toggle" type="button">Resize <span class="arrow">⌄</span></button><div class="submenu"><a href="/#resize">Image Resizer <span class="soon">AVAILABLE</span></a><a href="/#coming-soon">Bulk Image Resizer <span class="soon">COMING SOON</span></a></div></div><div class="menu-group"><button class="menu-toggle" type="button">Crop <span class="arrow">⌄</span></button><div class="submenu"><a href="/#coming-soon">Crop Image <span class="soon">COMING SOON</span></a></div></div><div class="menu-group"><button class="menu-toggle" type="button">Compress <span class="arrow">⌄</span></button><div class="submenu"><a href="/#coming-soon">Image Compressor <span class="soon">COMING SOON</span></a></div></div><div class="menu-group"><button class="menu-toggle" type="button">Convert <span class="arrow">⌄</span></button><div class="submenu"><a href="/#convert">Image Converter <span class="soon">COMING SOON</span></a><a href="/#coming-soon">JPG to PNG <span class="soon">COMING SOON</span></a><a href="/#coming-soon">PNG to JPG <span class="soon">COMING SOON</span></a><a href="/#coming-soon">WebP Converter <span class="soon">COMING SOON</span></a></div></div><div class="menu-group"><button class="menu-toggle" type="button">More <span class="arrow">⌄</span></button><div class="submenu"><a href="/#tools">Image Tools</a><a href="/#pdf">PDF Tools</a><a href="/#coming-soon">Rotate Image <span class="soon">COMING SOON</span></a><a href="/#coming-soon">Flip Image <span class="soon">COMING SOON</span></a><a href="/#coming-soon">Image Enlarger <span class="soon">COMING SOON</span></a></div></div></div><div class="menu-note">Resize is available now. Other tools are shown as Coming soon until fully implemented.</div></div>';b.addEventListener('click',function(e){e.stopPropagation();var open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));p.setAttribute('aria-hidden',String(open));p.classList.toggle('open',!open);document.body.style.overflow=open?'':'hidden'});p.addEventListener('click',function(e){var t=e.target;if(t.classList.contains('menu-toggle')){var g=t.parentElement;g.classList.toggle('open');return}if(t.closest('a')){b.setAttribute('aria-expanded','false');p.setAttribute('aria-hidden','true');p.classList.remove('open');document.body.style.overflow=''}})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();</script>`;
  html=html.replace(/<\/body>/i,script+"</body>");
  const headers=new Headers(response.headers);headers.delete("content-length");headers.delete("content-encoding");
  return new Response(html,{status:response.status,statusText:response.statusText,headers});
}
export default {async fetch(request,env,ctx){return fixMenu(await base.fetch(request,env,ctx));}};
