import ads from "./ads-entry.js";

const TOOLS_UI = `
<style id="akhisave-tools-manager-style">
#akhisave-tools-manager{margin-top:12px}.atm-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.atm-head h2{margin:0 0 5px;font-size:18px}.atm-head p{margin:0;color:#68778b;font-size:10px;line-height:1.6}.atm-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.atm-stat{padding:13px;border:1px solid #e4eaf2;border-radius:13px;background:#f7faff}.atm-stat b{display:block;font-size:19px;margin-top:4px;color:#0a1628}.atm-toolbar{display:grid;grid-template-columns:1.6fr 1fr 1fr auto;gap:8px;margin:12px 0}.atm-toolbar input,.atm-toolbar select,.atm-modal input,.atm-modal textarea,.atm-modal select{width:100%;padding:10px 11px;border:1px solid #d8e1ec;border-radius:10px;background:#fff;color:#0a1628;outline:0;font-size:10px}.atm-list{display:grid;gap:8px}.atm-tool{display:flex;align-items:center;gap:10px;padding:12px;border:1px solid #e4eaf2;border-radius:13px;background:#f7faff}.atm-icon{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:#edf5ff;font-size:18px;flex:none}.atm-main{flex:1;min-width:0}.atm-main b{font-size:11px;color:#0a1628}.atm-meta{display:block;color:#68778b;font-size:9px;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.atm-actions{display:flex;align-items:center;gap:5px;flex-wrap:wrap;justify-content:flex-end}.atm-actions button{border:1px solid #d8e1ec;background:#fff;color:#43536a;border-radius:8px;padding:6px 8px;font-size:9px;font-weight:800;cursor:pointer}.atm-actions button:hover{background:#edf5ff;color:#1677ff}.atm-actions .danger{color:#d33b4b}.atm-badge{font-size:8px;font-weight:850;padding:4px 7px;border-radius:999px;background:#e9faf3;color:#16864a;border:1px solid #bdebd6}.atm-badge.off{background:#fff1f2;color:#c72f42;border-color:#f3c5cb}.atm-empty{padding:22px;text-align:center;color:#68778b;font-size:10px;border:1px dashed #d8e1ec;border-radius:12px}.atm-modal-wrap{position:fixed;inset:0;background:#0008;z-index:1000;display:none;align-items:center;justify-content:center;padding:16px}.atm-modal-wrap.show{display:flex}.atm-modal{width:min(620px,100%);max-height:90vh;overflow:auto;padding:18px;border:1px solid #e4eaf2;border-radius:18px;background:#fff;box-shadow:0 30px 100px #0004;color:#0a1628}.atm-modal h3{margin:0 0 4px;font-size:18px}.atm-modal p{margin:0 0 14px;color:#68778b;font-size:10px}.atm-grid2{display:grid;grid-template-columns:1fr 1fr;gap:9px}.atm-modal label{display:block;color:#66758a;font-size:9px;font-weight:850;margin:0 0 5px}.atm-modal .field{margin:9px 0}.atm-modal textarea{min-height:70px;resize:vertical}.atm-modal-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:14px}.atm-modal-actions button{border:1px solid #d8e1ec;border-radius:10px;padding:9px 12px;background:#fff;color:#43536a;font-size:10px;font-weight:850;cursor:pointer}.atm-modal-actions .primary{border:0;background:linear-gradient(135deg,#1677ff,#16c9e8);color:#fff}
@media(max-width:760px){.atm-stats{grid-template-columns:1fr 1fr}.atm-toolbar{grid-template-columns:1fr 1fr}.atm-tool{display:grid;grid-template-columns:42px minmax(0,1fr) auto;align-items:center;gap:9px}.atm-badge{justify-self:end}.atm-actions{grid-column:1/-1;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;justify-content:stretch;padding-top:9px;border-top:1px solid #e4eaf2}.atm-actions button{width:100%;min-height:34px;padding:7px 5px;font-size:9px}.atm-tool>[data-tool-category]{grid-column:1/-1;grid-row:2;width:100%!important;max-width:none!important;box-sizing:border-box}.atm-grid2{grid-template-columns:1fr}}
@media(max-width:430px){.atm-toolbar{grid-template-columns:1fr}.atm-actions{grid-template-columns:repeat(2,minmax(0,1fr))}.atm-actions button:first-child,.atm-actions button:nth-child(2){grid-column:span 1}}
</style>
<section id="akhisave-tools-manager" class="card section">
  <div class="atm-head"><div><h2>Tools Management</h2><p>Control every registered tool: enable, disable, edit, reorder, add or remove.</p></div><button class="btn primary" id="atmAdd">+ Add Tool</button></div>
  <div class="atm-stats"><div class="atm-stat"><span class="label">TOTAL TOOLS</span><b id="atmTotal">—</b></div><div class="atm-stat"><span class="label">ENABLED</span><b id="atmEnabled">—</b></div><div class="atm-stat"><span class="label">DISABLED</span><b id="atmDisabled">—</b></div><div class="atm-stat"><span class="label">CUSTOM</span><b id="atmCustom">—</b></div></div>
  <div class="atm-toolbar"><input id="atmSearch" placeholder="Search tools…"><select id="atmPlatform"><option value="">All platforms</option><option value="instagram">Instagram</option><option value="youtube">YouTube</option><option value="tiktok">TikTok</option><option value="facebook">Facebook</option><option value="twitter">Twitter</option><option value="utility">Utility</option><option value="other">Other</option></select><select id="atmStatus"><option value="">All status</option><option value="on">Enabled</option><option value="off">Disabled</option></select><button class="btn secondary" id="atmReload">↻ Refresh</button></div>
  <div id="atmList" class="atm-list"><div class="atm-empty">Loading tools…</div></div>
</section>
<div id="atmModalWrap" class="atm-modal-wrap"><div class="atm-modal"><h3 id="atmModalTitle">Add Tool</h3><p>Save changes to the AkhiSave tool registry.</p><div class="atm-grid2"><div class="field"><label>Name</label><input id="atmName" maxlength="50"></div><div class="field"><label>Icon</label><input id="atmIcon" maxlength="8" placeholder="🧰"></div><div class="field"><label>Platform</label><select id="atmPlatformEdit"><option value="instagram">Instagram</option><option value="youtube">YouTube</option><option value="tiktok">TikTok</option><option value="facebook">Facebook</option><option value="twitter">Twitter</option><option value="utility">Utility</option><option value="other">Other</option></select></div><div class="field"><label>Engine</label><select id="atmEngine"><option value="social-url">Social URL</option><option value="image-crop">Image Crop</option><option value="image-pdf">Image to PDF</option><option value="image-compress">Image Compressor</option></select></div></div><div class="field"><label>Description</label><textarea id="atmDescription" maxlength="160"></textarea></div><div class="atm-grid2"><div class="field"><label>Button Text</label><input id="atmButton" maxlength="30"></div><div class="field"><label>Placeholder</label><input id="atmPlaceholder" maxlength="120"></div><div class="field"><label>Order</label><input id="atmOrder" type="number" min="0" max="9999"></div><div class="field"><label>Enabled</label><select id="atmEnabledEdit"><option value="true">Enabled</option><option value="false">Disabled</option></select></div></div><div class="atm-modal-actions"><button id="atmCancel">Cancel</button><button class="primary" id="atmSave">Save Tool</button></div></div></div>
`;

export default {
  async fetch(request, env, ctx) {
    const response = await ads.fetch(request, env, ctx);
    const url = new URL(request.url);
    if (request.method !== "GET" || (url.pathname !== "/admin.html" && url.pathname !== "/admin")) return response;
    const ct = response.headers.get("content-type") || "";
    if (!ct.includes("text/html")) return response;
    let html = await response.text();
    if (!/<title>AkhiSave Admin<\/title>/i.test(html)) return new Response(html,{status:response.status,headers:response.headers});
    const injection = TOOLS_UI + `<script>(function(){
      const $=id=>document.getElementById(id); let tools=[]; let editId=null;
      function esc(v){return String(v??"").replace(/[&<>\\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));}
      function showMsg(msg){if(typeof window.toast==='function')window.toast(msg);else alert(msg)}
      async function api(method,body){const r=await fetch('/api/admin/tools',{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||'Request failed');return d;}
      function stats(){ $('atmTotal').textContent=tools.length; $('atmEnabled').textContent=tools.filter(t=>t.enabled!==false).length; $('atmDisabled').textContent=tools.filter(t=>t.enabled===false).length; $('atmCustom').textContent=tools.filter(t=>!/^instagram-(photo|reels|video|story|dp)$/.test(String(t.id||''))).length; }
      function render(){stats();const q=$('atmSearch').value.trim().toLowerCase(),p=$('atmPlatform').value,s=$('atmStatus').value;const list=tools.slice().sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0)).filter(t=>(!q||[t.name,t.description,t.platform,t.id].some(x=>String(x||'').toLowerCase().includes(q)))&&(!p||t.platform===p)&&(!s||(s==='on'?t.enabled!==false:t.enabled===false)));if(!list.length){$('atmList').innerHTML='<div class="atm-empty">No tools match the current filter.</div>';return} $('atmList').innerHTML=list.map(t=>{const real=tools.findIndex(x=>x.id===t.id);return '<div class="atm-tool"><div class="atm-icon">'+esc(t.icon||'🧰')+'</div><div class="atm-main"><b>'+esc(t.name||'Untitled')+'</b><span class="atm-meta">'+esc(t.platform||'utility')+' · '+esc(t.engine||t.type||'social-url')+' · order '+(Number(t.order)||0)+'</span></div><span class="atm-badge '+(t.enabled===false?'off':'')+'">'+(t.enabled===false?'DISABLED':'ENABLED')+'</span><div class="atm-actions"><button data-act="up" data-i="'+real+'">↑</button><button data-act="down" data-i="'+real+'">↓</button><button data-act="edit" data-i="'+real+'">Edit</button><button data-act="toggle" data-i="'+real+'">'+(t.enabled===false?'Enable':'Disable')+'</button><button class="danger" data-act="delete" data-i="'+real+'">Delete</button></div></div>'}).join('');}
      function openModal(tool){editId=tool?.id||null;$('atmModalTitle').textContent=editId?'Edit Tool':'Add Tool';$('atmName').value=tool?.name||'';$('atmIcon').value=tool?.icon||'🧰';$('atmPlatformEdit').value=tool?.platform||'utility';$('atmEngine').value=tool?.engine||tool?.type||'social-url';$('atmDescription').value=tool?.description||'';$('atmButton').value=tool?.button||'Start';$('atmPlaceholder').value=tool?.placeholder||'Paste a URL';$('atmOrder').value=Number.isFinite(Number(tool?.order))?tool.order:(tools.length+1)*10;$('atmEnabledEdit').value=tool?.enabled===false?'false':'true';$('atmModalWrap').classList.add('show');}
      function closeModal(){$('atmModalWrap').classList.remove('show');editId=null;}
      async function saveTool(){const name=$('atmName').value.trim();if(!name){showMsg('Tool name is required.');return}const id=editId||('tool-'+Date.now());const t={id,name,icon:$('atmIcon').value.trim()||'🧰',platform:$('atmPlatformEdit').value,engine:$('atmEngine').value,type:$('atmEngine').value,enabled:$('atmEnabledEdit').value==='true',description:$('atmDescription').value.trim(),button:$('atmButton').value.trim()||'Start',placeholder:$('atmPlaceholder').value.trim()||'Paste a URL',order:Number($('atmOrder').value)||0};const idx=tools.findIndex(x=>x.id===editId);if(idx>=0)tools[idx]={...tools[idx],...t};else tools.push(t);try{await api('PUT',{tools});closeModal();await load();showMsg('Tool saved.')}catch(e){showMsg(e.message)}}
      async function load(){try{const d=await api('GET');tools=Array.isArray(d.tools)?d.tools:[];render()}catch(e){$('atmList').innerHTML='<div class="atm-empty">Could not load tools: '+esc(e.message)+'</div>'}}
      async function act(e){const b=e.target.closest('button[data-act]');if(!b)return;const i=Number(b.dataset.i),a=b.dataset.act;if(!tools[i])return;if(a==='edit'){openModal(tools[i]);return}if(a==='delete'){if(!confirm('Delete this tool from the registry?'))return;tools.splice(i,1)}else if(a==='toggle'){tools[i].enabled=tools[i].enabled===false}else if(a==='up'&&i>0){[tools[i-1],tools[i]]=[tools[i],tools[i-1]]}else if(a==='down'&&i<tools.length-1){[tools[i+1],tools[i]]=[tools[i],tools[i+1]]}else return;tools.forEach((t,n)=>t.order=(n+1)*10);try{await api('PUT',{tools});render();showMsg('Tool registry updated.')}catch(err){showMsg(err.message);await load()}}
      function init(){const old=$('tools');if(old)old.style.display='none';$('atmAdd').onclick=()=>openModal();$('atmCancel').onclick=closeModal;$('atmModalWrap').addEventListener('click',e=>{if(e.target.id==='atmModalWrap')closeModal()});$('atmSave').onclick=saveTool;$('atmReload').onclick=load;$('atmSearch').oninput=render;$('atmPlatform').onchange=render;$('atmStatus').onchange=render;$('atmList').addEventListener('click',act);load();}
      if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
    })();</script>`;
    html = html.replace(/<section id="tools"[\s\S]*?(?=<section id="settings")/i, `<section id="tools" class="tab"><div class="hero"><div><h1>Tools</h1><p>Manage all registered AkhiSave tools.</p></div></div>${injection}</section>`);
    if (!html.includes('id="akhisave-tools-manager"')) html = html.replace(/<main class="wrap">/i, `<main class="wrap">${injection}`);
    const headers = new Headers(response.headers); headers.delete("content-length"); headers.set("Cache-Control","no-store");
    return new Response(html,{status:response.status,headers});
  }
};
